[window]
dimensions.columns = 200
dimensions.lines = 100
padding.x = 30
padding.y = 25
decorations = "none"
opacity = 0.85

[font]
size = 18.0

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[colors.primary]
background = "#0F0E0E"
foreground = "#f2e5bc"

[colors.normal]
black   = "#1d2021"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#f2e5bc"
